### ISSUE TITLE
Not seeing accessory

### ISSUE THREAD

**Issue by gonzonia** [fisherwise/homebridge-switchmate-switch#2]
**Describe Your Problem:**
After installing the plugin and adding the switch I don't see the accessory added. 
**Logs:**

```
[12/29/2020, 1:55:35 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/29/2020, 1:55:35 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 35421
[12/29/2020, 1:55:36 PM] Loaded config.json with 1 accessories and 7 platforms.
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-bravia@2.4.7
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-bravia.BraviaPlatform'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-config-ui-x.config'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-nest@4.5.1
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-nest.Nest'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-ring@9.12.8
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-ring.Ring'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-samsungtv-control@2.0.0
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:36 PM] Loaded plugin: homebridge-switchmate-switch@1.1.0
[12/29/2020, 1:55:36 PM] Registering platform 'homebridge-switchmate-switch.SwitchmateSwitch'
[12/29/2020, 1:55:36 PM] ---
[12/29/2020, 1:55:37 PM] ---
[12/29/2020, 1:55:37 PM] Loaded plugin: homebridge-tplink-smarthome@6.1.0
[12/29/2020, 1:55:37 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[12/29/2020, 1:55:37 PM] ---
[12/29/2020, 1:55:37 PM] Loaded plugin: homebridge-yamaha-receiver@0.0.6
[12/29/2020, 1:55:37 PM] Registering platform 'homebridge-yamaha-receiver.YamahaReceiver'
[12/29/2020, 1:55:37 PM] ---
[12/29/2020, 1:55:37 PM] Loading 7 platforms...
[12/29/2020, 1:55:37 PM] [Config] Initializing config platform...
[12/29/2020, 1:55:37 PM] [Config] Running in Service Mode
[12/29/2020, 1:55:37 PM] [Ring] Initializing Ring platform...
[12/29/2020, 1:55:37 PM] [Nest] Initializing Nest platform...
[12/29/2020, 1:55:37 PM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[12/29/2020, 1:55:37 PM] [TplinkSmarthome] homebridge-tplink-smarthome v6.1.0, node v14.15.3, homebridge v1.1.7
[12/29/2020, 1:55:37 PM] [BraviaPlatform] Initializing BraviaPlatform platform...
[12/29/2020, 1:55:37 PM] [YamahaReceiver] Initializing YamahaReceiver platform...
[12/29/2020, 1:55:37 PM] [SwitchmateSwitch] Initializing SwitchmateSwitch platform...
[12/29/2020, 1:55:37 PM] Loading 1 accessories...
[12/29/2020, 1:55:37 PM] [BraviaPlatform] Restoring Family Room TV from HomeKit
[12/29/2020, 1:55:37 PM] [Nest] Fetching Nest devices.
[12/29/2020, 1:55:37 PM] Homebridge is running on port 51155.
[12/29/2020, 1:55:37 PM] [YamahaReceiver] Found AVR "Yamaha RX-A1070" at XX
HAP Warning: Characteristic E863F126-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10C-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F110-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10A-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10D-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F126-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10C-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F110-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10A-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10D-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/29/2020, 1:55:37 PM] Yamaha AV is running on port 50906.
[12/29/2020, 1:55:37 PM] Please add [Yamaha AV] manually in Home app. Setup Code: XX
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/29/2020, 1:55:37 PM] Zone2 is running on port 50907.
[12/29/2020, 1:55:37 PM] Please add [Zone2] manually in Home app. Setup Code:XX
[12/29/2020, 1:55:38 PM] [Ring] Configuring 1 cameras and 4 devices for location "Tampa" - locationId: XX
[12/29/2020, 1:55:40 PM] [Nest] initing thermostat "Downstairs Thermostat": deviceId: XX structureId:XX
[12/29/2020, 1:55:40 PM] [Nest] initing thermostat (P) "Upstairs Thermostat": deviceId: XX structureId: XX
[12/29/2020, 1:55:40 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId:XX structureId: X
[12/29/2020, 1:55:40 PM] [Nest] initing protect "Upstairs": deviceId: XX structureId: XX
[12/29/2020, 1:55:40 PM] [Nest] initing protect "Downstairs": deviceId: XX structureId: XX
```

**Plugin Config:**

```      
        {
            "devices": [
                {
                    "name": "Master Bedroom",
                    "id": "MAC ID (Double and triple checked)"
                }
            ],
            "platform": "SwitchmateSwitch"
        }
```

**Environment:**

* **Plugin Version**:  homebridge-switchmate-switch v1.1.0
* **Homebridge Version**: 1.17
* **Node.js Version**: v14.15.3
* **NPM Version**: 6.14.9
* **Operating System**: macOS

**Comment by oovz** [comment]
looks like the plugin never finished initialization. Is this the log in debug mode?

**Comment by gonzonia** [comment]
No. Not debug. I set Debug to * and I'm not sure I can weed through that to pull out everything that needs to be pulled for privacy. Any way to guide me what to look for?

**Comment by oovz** [comment]
you can turn on the debug mode(not setting debug environment variable) then copy all lines starting with ```[SwitchmateSwitch]```. you can mark anything that looks like a mac address to you.

**Comment by gonzonia** [comment]
```

[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39mInitializing SwitchmateSwitch platform...
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mFinished initializing platform[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mExecuted didFinishLaunching callback[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 5d23eeb4f6554650b9d98f6695a0a997 is not configured[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 33103bb138af4b03974c5abccaf75cdb is not configured[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 2408c374f2db426bad43b6ad34eb3010 is not configured[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 460bac18ea7844de8a6edc494e2f047b is not configured[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral b3983b47956648cdbd5e9a794cf91e81 is not configured[39m
[37m[12/29/2020, 10:50:52 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 17f673b4ac3e42428d03736c2a5f1d01 is not configured[39m
[37m[12/29/2020, 10:50:53 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral b329c7ed14644a4f83953e844bea93b0 is not configured[39m
[37m[12/29/2020, 10:50:53 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 241c9f36660c4ab0bb288e1f50638407 is not configured[39m
[37m[12/29/2020, 10:50:53 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral a4453abf79dc4bd1992561b2dbeef0a9 is not configured[39m
[37m[12/29/2020, 10:50:53 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 46737e251227465f994366c474af5c65 is not configured[39m
[37m[12/29/2020, 10:50:53 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 33437f4e699e402191e2ff88d4e6c858 is not configured[39m
[37m[12/29/2020, 10:50:54 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 65502d2d7c22452ebc758487cfaa3ee4 is not configured[39m
[37m[12/29/2020, 10:50:54 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 6529a4cee1024493ac5de8849eb72da6 is not configured[39m
[37m[12/29/2020, 10:50:55 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 5a91ab5cedf241c6ad1ed9413472bc88 is not configured[39m
[37m[12/29/2020, 10:50:55 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 7b5771be4f554b5bb7599d0338f1770b is not configured[39m
[37m[12/29/2020, 10:50:56 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral d807b6cb343d46de9e250a3c596b5688 is not configured[39m
[37m[12/29/2020, 10:50:57 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 29fc38c976164fb6bcec5c1bdefb8bd6 is not configured[39m
[37m[12/29/2020, 10:50:59 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 11949155a2ed4e8194f5b0765df5d2be is not configured[39m
[37m[12/29/2020, 10:50:59 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 040ba6b162d744df8448e2c2e4a73c6c is not configured[39m
[37m[12/29/2020, 10:51:03 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral d291606134a44897bda672d58df496bb is not configured[39m
[37m[12/29/2020, 10:51:03 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 3fd1f921e873433899b307602b7525a6 is not configured[39m
[37m[12/29/2020, 10:51:05 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 773a9038973b4116b06d3d7138a1ec59 is not configured[39m
[37m[12/29/2020, 10:51:11 PM] [39m[36m[SwitchmateSwitch] [39m[90mperipheral 9824745086554d628011cf9421fee8e4 is not configured[39m

```

**Comment by oovz** [comment]
thanks. looks like it does discover some bluetooth devices but the mac addresses are not in a format that this plugin can understand. they should be something like ```5f06d9e88cd2 ```.
Are you running homebridge on a pi?

**Comment by gonzonia** [comment]
No. On a Mac. Maybe it’s not picking up the switch just being too far away?

**Comment by oovz** [comment]
no. the plugin is looking for something like ```5f06d9e88cd2```. Are you installing noble with homebrew?
Looking at their page I don't find anything regarding macOS yet it supports macOS [link](https://github.com/abandonware/noble#os-x)

**Comment by gonzonia** [comment]
MacOS is at the top. It just says install Xcode which I verified I have installed. I’ll see if I can find more info down that path. Thanks for the help.

**Comment by gonzonia** [comment]
Looking through the code examples though there are a bunch of notes regarding MacOS. Don’t know what may or may not apply to your code. 
example: Note: isNotification event parameter value MAY be undefined depending on platform. The parameter is deprecated after version 1.8.1, and not supported on macOS High Sierra and later.

And 

Note: On macOS, the address will be set to '' if the device has not been connected previously.

**Comment by oovz** [comment]
that's why I'm not sure. There's nothing special regarding the usage of noble on macOS, yet it's outputing something different from linux/raspbian. 

> Note: On macOS, the address will be set to '' if the device has not been connected previously.

this doesn't matter to us since we're using the ```id``` of the device not the ```address```

**Comment by oovz** [comment]
I'll try to see if I can find the problem on my macbook but I'm pretty busy this week so hopefully next week

**Comment by gonzonia** [comment]
I'm going to move to Big Sur and update Xcode too, see if that helps.

**Comment by gonzonia** [comment]
This is all I'm seeing now (I don't know that it's related to the updates). 
`[37m[1/2/2021, 4:29:49 PM] [39mLoaded plugin: homebridge-switchmate-switch@1.1.0
[37m[1/2/2021, 4:29:49 PM] [39mRegistering platform 'homebridge-switchmate-switch.SwitchmateSwitch'
[37m[1/2/2021, 4:29:49 PM] [39mRegistering platform 'homebridge-switchmate-switch.SwitchmateSwitch'
[37m[1/2/2021, 4:29:49 PM] [39m[36m[SwitchmateSwitch] [39mInitializing SwitchmateSwitch platform...
[37m[1/2/2021, 4:29:49 PM] [39m[36m[SwitchmateSwitch] [39mInitializing SwitchmateSwitch platform...
[37m[1/2/2021, 4:29:49 PM] [39m[36m[SwitchmateSwitch] [39m[90mFinished initializing platform[39m
[37m[1/2/2021, 4:29:49 PM] [39m[36m[SwitchmateSwitch] [39m[90mExecuted didFinishLaunching callback[39m
[37m[1/2/2021, 4:29:49 PM] [39m[36m[SwitchmateSwitch] [39m[90mstart noble scanning[39m
`

**Comment by oovz** [comment]
hi @gonzonia, i just updated the plugin with more detailed logs. Please update and see if you get more logs from homebridge.

**Comment by gonzonia** [comment]
I looked at this some more earlier today. I have some theories....
#1- Noble added some details to their requirements. They added a note about needing to update security settings on OSX. 
#2- I looked at another [Switchmate plugin](https://github.com/AMoo-Miki/homebridge-switchmate-ble) and and they had some additional steps that won't work on MacOS. I'm wondering if some of that is to blame. 

In my logs now.
[1/24/2021, 7:06:18 PM] [SwitchmateSwitch] Initializing SwitchmateSwitch platform...
[1/24/2021, 7:06:18 PM] [SwitchmateSwitch] Finished initializing platform
[1/24/2021, 7:06:18 PM] [SwitchmateSwitch] on DID_FINISH_LAUNCHING. Looking for new accessories
[1/24/2021, 7:06:18 PM] [SwitchmateSwitch] delay discovery for 15 seconds

[1/24/2021, 7:06:33 PM] [SwitchmateSwitch] noble is not running. waiting for it to power on...

**Comment by oovz** [comment]
> #2- I looked at another [Switchmate plugin](https://github.com/AMoo-Miki/homebridge-switchmate-ble) and and they had some additional steps that won't work on MacOS. I'm wondering if some of that is to blame.

I don't see the additional steps. mind referring those?

for the logs is that all you get from the plugin? Normally the scan should start following your last line.

**Comment by gonzonia** [comment]
From the other plugin - This can't be run on MacOS. 
> Permissions
> NodeJS needs permission to control the Bluetooth radio on your system. Execute the command below to give NodeJS the capability use raw sockets and manage the interface.
> 
> sudo setcap 'cap_net_raw,cap_net_admin+eip' `which node`

That's it from the logs.

**Comment by oovz** [comment]
maybe they removed the 'undocumented protocol' mentioned [here](https://github.com/Timeular/noble-mac)

**Comment by oovz** [comment]
not sure if this is the issue you have abandonware/noble#162

**Comment by gonzonia** [comment]
That's the security changes I referred to. I made the change, but still no go. I've installed the plugin (is there an install log somewhere?) but no accessories. I think this is likely the issue because an npm install in the homebridge folder (from ssh or terminal directly) results in 

```
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @abandonware/bluetooth-hci-socket@0.5.3-6 (node_modules/@abandonware/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @abandonware/bluetooth-hci-socket@0.5.3-6: wanted {"os":"linux,android,freebsd,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
```

So I think the issue is the that it's being accessed from something other than terminal and I need to determine what and give it appropriate permissions.

**Comment by oovz** [comment]
> I think this is likely the issue because an npm install in the homebridge folder (from ssh or terminal directly) results in

it shouldn't be because these 2 are optional dependencies.

if you install the plugin you [referred](https://github.com/AMoo-Miki/homebridge-switchmate-ble) they have a binary tool that scans BLE devices. Have you tried that? Does it work?

**Comment by gonzonia** [comment]
No. I posted an issue on that plugin as well. 

> I tried just installing and running switchmate-ble find
> This is the result
> 
> /usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:28
>         noble._bindings._hci.on('leScanEnableSetCmd', enabled => {
>                              ^
> 
> TypeError: Cannot read property 'on' of undefined
>     at new Scanner (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:28:30)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/lib/scanner.js:224:28)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate-ble/bin/cli-find.js:4:17)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by oovz** [comment]
Hi @gonzonia

Not sure if you still have this problem. I've upgraded my pi4 to bullseye and had the same problem.
Upon checking the bluetooth service is not running due to the new ```connman``` cli tool added.

This might be the same problem for you. Can you please check if the bluetooth service corrected started?
You can do so by using ```sudo systemctl status bluetooth```

**Comment by gonzonia** [comment]
I actually stopped using homebridge and switched over to Home Assistant which had broader support for my devices. I couldn't get the Switchmate device working their either,  but it's not a big deal.

**Comment by oovz** [comment]
Okay I'll close this then. Let me know if you're switching back and we can try debug it.
